#!/usr/bin/env bash

show_usage () {
    echo "Usage: Please use one of the following:
./run setup
./run dev
./run credo
./run test
./run release"
    exit 1
}

if [ $# -eq 0 ];then
    show_usage
    exit 1
fi

while [ ! -z "$1" ];do
    case "$1" in
        setup)
            shift
            nix-shell --run "echo \"export PGDATA=\$PWD/pg-data\" >> .envrc &&
                echo \"export PGHOST=\$PWD/pg-localhost\" >> .envrc &&
                echo \"export LOG_PATH=\$PWD/pg-localhost/LOG\" >> .envrc &&
                echo \"export PGDATABASE=postgres\" >> .envrc &&
                echo \"export PGUSER=postgres\" >> .envrc &&
                echo \"export DATABASE_URL=\"postgresql:///postgres?host=\$PWD/pg-localhost\"\" >> .envrc &&
                sh ./pg-local start &
                source .envrc &&
                mix local.hex --force &&
                mix local.rebar --force &&
                mix deps.get &&
                mix ecto.setup &&
                yarn --cwd assets install &&
                iex -S mix phx.server"
            ;;
        dev)
            shift
            nix-shell --run "sh ./pg-local start &
                source .envrc &&
                iex -S mix phx.server"
            ;;
        release)
            shift
                nix-shell --run "sh ./pg-local start &
                source .envrc &&
                yarn --cwd assets deploy &&
                mix deps.get --only prod &&
                mix ecto.migrate &&
                mix phx.digest &&
                mix release"
                ;;
        credo)
            shift
            nix-shell --run "mix credo"
            ;;
        test)
            shift
            nix-shell --run "chromedriver & mix test"
            ;;
        *)
            shift
            show_usage
            ;;
    esac
    shift
done
exit 0
