#!/usr/bin/env bash

show_usage () {
    echo "Usage: Please use one of the following:
./run setup
./run dev
./run credo
./run test
./run release"
    exit 1
}

if [ $# -eq 0 ];then
    show_usage
    exit 1
fi

while [ ! -z "$1" ];do
    case "$1" in
        setup)
            shift
            nix-shell --run "echo \"export LANG=en_US.UTF-8\" > .envrc &&
                echo \"export LC_CTYPE=en_US.UTF-8\" >> .envrc &&
                echo \"export LC_NUMERIC=en_US.UTF-8\" >> .envrc &&
                echo \"export LC_TIME=en_US.UTF-8\" >> .envrc &&
                echo \"export LC_COLLATE=en_US.UTF-8\" >> .envrc &&
                echo \"export LC_MONETARY=en_US.UTF-8\" >> .envrc &&
                echo \"export LC_MESSAGES=en_US.UTF-8\" >> .envrc &&
                echo \"export LC_PAPER=en_US.UTF-8\" >> .envrc &&
                echo \"export LC_NAME=en_US.UTF-8\" >> .envrc &&
                echo \"export LC_ADDRESS=en_US.UTF-8\" >> .envrc &&
                echo \"export LC_TELEPHONE=en_US.UTF-8\" >> .envrc &&
                echo \"export LC_MEASUREMENT=en_US.UTF-8\" >> .envrc &&
                echo \"export LC_IDENTIFICATION=en_US.UTF-8\" >> .envrc &&
                echo \"export LC_ALL=\" >> .envrc &&
                echo \"export PGDATA=\$PWD/pg-data\" >> .envrc &&
                echo \"export PGHOST=\$PWD/pg-localhost\" >> .envrc &&
                echo \"export LOG_PATH=\$PWD/pg-localhost/LOG\" >> .envrc &&
                echo \"export PGDATABASE=postgres\" >> .envrc &&
                echo \"export PGUSER=postgres\" >> .envrc &&
                echo \"export DATABASE_URL=\"postgresql:///postgres?host=\$PWD/pg-localhost\"\" >> .envrc &&
                sh ./pg-local start &
                source .envrc &&
                mix local.hex --force
                mix local.rebar --force
                mix deps.get &&
                mix ecto.setup &&
                yarn --cwd assets install &&
                iex -S mix phx.server"
            ;;
        dev)
            shift
            nix-shell --run "sh ./pg-local start &
                iex -S mix phx.server"
            ;;
        release)
            shift
            nix-shell --run "sh ./pg-local start &
                yarn --cwd assets deploy &&
                mix deps.get --only prod &&
                mix ecto.migrate &&
                mix phx.digest &&
                mix release"
            ;;
        credo)
            shift
            nix-shell --run "mix credo"
            ;;
        test)
            shift
            nix-shell --run "chromedriver & mix test"
            ;;
        *)
            shift
            show_usage
            ;;
    esac
    shift
done
exit 0
